// translated by Mr_KrzYch00

CREDITS_LINE("Ludzie bioracy udzial w produkcji i grze: ", 460),
CREDITS_LINE("Plansza 1:", 540),
CREDITS_LINE("Senpai　Ｘ～Ｚ", 590),
CREDITS_LINE("Plansza 2:", 650),
CREDITS_LINE("Przyjaciel willowlet", 700),
CREDITS_LINE("Plansza 3:", 760),
CREDITS_LINE("Przyjaciel willowlet", 810),
CREDITS_LINE("Plansza 4:", 870),
CREDITS_LINE("2 przyjaciel　ann ", 920),
CREDITS_LINE("Pomoc:", 1000),
CREDITS_LINE("Ｔ-senpai ", 1050),
CREDITS_LINE("Ｓ-senpai ", 1100),
CREDITS_LINE("Producent animacji: ", 1180),
CREDITS_LINE("Ｋ-senpai ", 1230),
CREDITS_LINE("Przechwytywanie animacji, edycja, kodowanie:", 1360),
CREDITS_LINE("willowlet ", 1410),
CREDITS_LINE("Programowanie, rysowanie, kawaly, edycja animacji:", 1540),
CREDITS_LINE("Chiku ", 1590),
CREDITS_LINE("Dziekuje za granie～", 1800),