MISC_TEXT(TEXT_PRESS_START, "STARTボタンを押せ!!"),

MISC_TEXT(TEXT_NO_CONTROLLER, "NO CONTROLLER!"),

MISC_TEXT(TEXT_STAGE_NUM, "ステージ %d"),

MISC_TEXT(TEXT_MYSTERY_DUNGEON, "不思議ダンジョン"),

MISC_TEXT(TEXT_PAUSED, "ポーズ中"),

MISC_TEXT(TEXT_CONTINUE, "つづける"),

MISC_TEXT(TEXT_GO_TO_TITLE, "タイトルにもどる"),

MISC_TEXT(TEXT_GAME_CLEAR, "ゲームクリアー"),

MISC_TEXT(TEXT_THANKS_FOR_PLAYING, "プレイしてくれてありがとー"),