// translated by Mr_KrzYch00

CREDITS_LINE("People involved in production and play: ", 460),
CREDITS_LINE("Stage 1 play: ", 540),
CREDITS_LINE("Senpai　Ｘ～Ｚ", 590),
CREDITS_LINE("Stage 2 play: ", 650),
CREDITS_LINE("Friend willowlet ", 700),
CREDITS_LINE("Stage 3 play: ", 760),
CREDITS_LINE("Friend willowlet ", 810),
CREDITS_LINE("Stage 4 play: ", 870),
CREDITS_LINE("2nd friend　ann", 920),
CREDITS_LINE("Helpers:", 1000),
CREDITS_LINE("Ｔ-senpai ", 1050),
CREDITS_LINE("Ｓ-senpai ", 1100),
CREDITS_LINE("Animation producer: ", 1180),
CREDITS_LINE("Ｋ-senpai ", 1230),
CREDITS_LINE("Animation capture, editing, encoding: ", 1360),
CREDITS_LINE("willowlet ", 1410),
CREDITS_LINE("Programming, drawing, jokes, animation editing: ", 1540),
CREDITS_LINE("Chiku ", 1590),
CREDITS_LINE("Thank you for playing～ ", 1800),