MISC_TEXT(TEXT_PRESS_START, "Press START!!"),

MISC_TEXT(TEXT_NO_CONTROLLER, "NO CONTROLLER!"),

MISC_TEXT(TEXT_STAGE_NUM, "Stage number: %d"),

MISC_TEXT(TEXT_MYSTERY_DUNGEON, "Mystery Dungeon"),

MISC_TEXT(TEXT_PAUSED, "PAUSED"),

MISC_TEXT(TEXT_CONTINUE, "Continue"),

MISC_TEXT(TEXT_GO_TO_TITLE, "Go to title screen"),

MISC_TEXT(TEXT_GAME_CLEAR, "GAME CLEAR"),

MISC_TEXT(TEXT_THANKS_FOR_PLAYING, "Thanks for playing!!"),